### ISSUE TITLE
Assets for readme.md

### ISSUE THREAD

**Issue by danema** [danema/vimkickstart#4]
<img width="1919" alt="screen shot 2017-05-09 at 14 40 21" src="https://cloud.githubusercontent.com/assets/962263/25851310/95990e94-34c5-11e7-859c-9bf6d0983f0c.png">

**Comment by iPet** [comment]
![screen shot 2017-05-09 at 3 42 52 pm](https://cloud.githubusercontent.com/assets/3941358/25853792/409ad45a-34ce-11e7-8b3f-68fae4fe09c2.png)
